[loggers]
keys=root,uvicorn,httpx,httpcore

#################################
# LOGGERS
#################################

[logger_root]
level=INFO
handlers=console

[logger_uvicorn]
qualname=uvicorn
level=INFO
handlers=console
propagate=0

[logger_httpx]
qualname=httpx
level=WARNING
handlers=console
propagate=0

[logger_httpcore]
qualname=httpcore
level=WARNING
handlers=console
propagate=0

#################################
# HANDLERS
#################################

[handlers]
keys=console

[handler_console]
class=logging.StreamHandler
level=DEBUG
formatter=plain
stream=ext://sys.stderr

#################################
# FORMATTERS
#################################

[formatters]
keys=plain

[formatter_plain]
format=%(asctime)s | %(levelname)-8s | %(process)d | %(thread)d | %(name)s | %(message)s
datefmt=%Y-%m-%d %H:%M:%S
